package com.space.munova.product.domain.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum EventType {
    PRODUCT_LIKE("PRODUCT_LIKE"),
    PRODUCT_DISLIKE("PRODUCT_DISLIKE"),
    SAVE_PRODUCT_SYNC_MONGO("SAVE_PRODUCT_SYNC_MONGO"),
    SAVE_PRODUCT_SYNC_ES("SAVE_PRODUCT_SYNC_ES"),
    UPDATE_PRODUCT_SYNC_MONGO("UPDATE_PRODUCT_SYNC_MONGO"),
    UPDATE_PRODUCT_SYNC_ES("UPDATE_PRODUCT_SYNC_ES"),
    DELETE_PRODUCT_SYNC_MONGO("DELETE_PRODUCT_SYNC_MONGO"),
    DELETE_PRODUCT_SYNC_ES("DELETE_PRODUCT_SYNC_ES"),
    DELETE_PRODUCT_LIKE("DELETE_PRODUCT_LIKE"),
    DELETE_PRODUCT_CART("DELETE_CART");
    private final String value;
}
